### PR TITLE
is210-week-02-synthesizing 

### PR DESCRIPTION
**Pull request by heidyvl**

### CODE REVIEW

**Comment by cheuschober** [comment]
@heidyvl, Please join the GitHub team. Your tests won't run without it.

**Comment by heidyvl** [comment]
@cheuschober I just joined it. Thanks

**Comment by cheuschober** [comment]
ok to test

**Comment by cheuschober** [comment]
@heidyvl, Tests? Who needs automated tests? Certainly not you! Excellent job yet again. :) In the future the automated tests will fire within 15s of your opening your request (now that you've joined the team)

**Pull request merged**
