### PR TITLE
Created two new files

### PR DESCRIPTION
**Pull request by smajid**
Following Professor's step by step directions I created two files, committed them and created a pull request.

### CODE REVIEW

**Comment by cheuschober** [comment]
ok to test

**Comment by smajid** [comment]
?I tried the link, my computer said that it's not secure and led me back. What to do next? Do I disable the firewall?


Saulat


_____________________

Saulat Majid
571.291.5913
________________________________

**Comment by cheuschober** [comment]
If you receive that message, you can just proceed and/or add it to your whitelist.

**Comment by smajid** [comment]
Professor, two queries;
1. Do I need to add an additional file, like you added at the end
2. For Assignment#2 warm-up, due on Friday, do all I need to post is the link above
Please advise.

**Comment by smajid** [comment]
Sorry, I don't get this testing part...what do I do to complete this?

**Comment by cheuschober** [comment]
@smajid

1. see below

2. yes, the link you would post is the link from this page or a page like this, your pull request page.

I'm going to close this pull request if only because it looks like you followed along the video but didn't actually do the tasks in the synthesizing lesson which have their own steps. Also, this is the synthesizing lesson, not the warm-up lesson. You might have accidentally clicked the wrong one!

Be sure to read the directions on the repository page. For example, the warmup page has its directions here and its link:

https://github.com/is210-2015-spring-01/is210-week-02-warmup

If you want to delete the files you added incorrectly here...

    $ git rm goodbye.txt hello.txt
    $ git commit -m "Removed files from video."

**Comment by smajid** [comment]
?

I get it, my bad! So do I just close my LXTerminal and open a new one to begin with the warm up tasks?

Please advise.


Saulat


_____________________

Saulat Majid
571.291.5913
________________________________

**Comment by cheuschober** [comment]
@smajid, When you close LXTerminal all the files you created are still there. You can probably see them on your Desktop in folders. So you'll probably want to move your terminal location to the desktop. You can see your current location by typing:

    $ pwd

If if doesn't end in `Desktop`, you're probably not there and will need to `cd` to the correct directory. For a refresher on some terminal commands you can see the Week One supplemental materials. Once you've gotten back to the desktop, fork the warmup repository on Github and execute a new `git clone` with the warmup repository. Make sure the name of the folder ends in `-warmup`

**Comment by smajid** [comment]
?Got it, Professor. Thanks!


Saulat


_____________________

Saulat Majid
571.291.5913
________________________________

**Comment by smajid** [comment]
?Professor,

Do I also need to fork this, before cloning?

So sorry to bug you at this hour...

Saulat


_____________________

Saulat Majid
571.291.5913
________________________________

**Comment by cheuschober** [comment]
@smajid, please see my last comment for more details.

**Pull request closed without merging**
